include ../Makefile.inc
# DO NOT DELETE

main.o: /home/uwe/Documents/git/stce/cppNum/v2.3/apps/sphere/sphere.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v2.3/cppNum/convexObjective/objective.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v2.3/cppNum/linearAlgebra.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v2.3/cppNum/convexObjective/gradientDescent.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v2.3/cppNum/convexObjective/minimizer.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v2.3/cppNum/approximation.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v2.3/cppNum/iteration.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v2.3/cppNum/linearAlgebra.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v2.3/cppNum/convexObjective/objective.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v2.3/cppNum/derivative.hpp
