# info@stce.rwth-aachen.de

all :
	cd differentialEquation && make
	cd casestudies && make
test :
	cd differentialEquation && make test
	cd casestudies && make test
depend :
	cd differentialEquation && make depend
	cd casestudies && make depend
clean :
	cd differentialEquation && make clean
	cd casestudies && make clean

.PHONY: all test depend clean
