include ../Makefile.inc

# DO NOT DELETE

main.o: intersection.hpp
main.o: $(BASE_DIR)/cppNum/algebraicSystem/system.hpp
main.o: $(BASE_DIR)/cppNum/linearAlgebra.hpp
main.o: $(BASE_DIR)/cppNum/algebraicSystem/newton.hpp
main.o: $(BASE_DIR)/cppNum/algebraicSystem/solver.hpp
main.o: $(BASE_DIR)/cppNum/approximation.hpp
main.o: $(BASE_DIR)/cppNum/iteration.hpp
main.o: $(BASE_DIR)/cppNum/linearAlgebra.hpp
main.o: $(BASE_DIR)/cppNum/derivative.hpp
