include ../../Makefile.inc
# DO NOT DELETE

main.o: /home/uwe/Documents/git/stce/cppNum/v2.4/apps/sphere/sphere.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v2.4/cppNum/convexObjective/objective.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v2.4/cppNum/convexObjective/newton.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v2.4/cppNum/convexObjective/minimizer.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v2.4/cppNum/approximation.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v2.4/cppNum/iteration.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v2.4/cppNum/linearAlgebra.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v2.4/cppNum/derivative.hpp
