include ../Makefile.inc
# DO NOT DELETE

main.o: ./sphere.hpp
main.o: ../../cppNum/convexObjective/objective.hpp
main.o: ../../cppNum/convexObjective/newton.hpp
main.o: ../../cppNum/convexObjective/minimizer.hpp
main.o: ../../cppNum/approximation.hpp
main.o: ../../cppNum/iteration.hpp
main.o: ../../cppNum/linearAlgebra.hpp
main.o: ../../cppNum/derivative.hpp
main.o: ../../cppNum/exceptions/is_approx.hpp
main.o: ../../cppNum/exceptions/logic_error.hpp
main.o: ../../cppNum/exceptions/math_error.hpp
