include ../../Makefile.inc

# DO NOT DELETE

main.o: ../../objectives/f1.hpp
main.o: ../../../cppNum/convexObjective/objective.hpp
main.o: ../../../cppNum/convexObjective/newton.hpp
main.o: ../../../cppNum/convexObjective/minimizer.hpp
main.o: ../../../cppNum/approximation.hpp
main.o: ../../../cppNum/iteration.hpp
main.o: ../../../cppNum/iteration.cpp
main.o: ../../../cppNum/convexObjective/minimizer.cpp
main.o: ../../../cppNum/convexObjective/objective.hpp
main.o: ../../../cppNum/convexObjective/newton.cpp
main.o: ../../../cppNum/derivative.hpp
main.o: ../../../cppNum/algebraicEquation/newton.hpp
main.o: ../../../cppNum/algebraicEquation/solver.hpp
main.o: ../../../cppNum/algebraicEquation/equation.hpp
main.o: ../../../cppNum/algebraicEquation/solver.cpp
