include ../Makefile.inc

# DO NOT DELETE

main.o: /home/uwe/Documents/git/stce/cppNum/v1.5/apps/equations/g1.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.5/cppNum/differentialEquation/equation.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.5/cppNum/differentialEquation/implicitEuler.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.5/cppNum/differentialEquation/integrator.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.5/cppNum/evolution.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.5/cppNum/iteration.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.5/cppNum/differentialEquation/implicitEuler.cpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.5/cppNum/algebraicEquation/newton.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.5/cppNum/algebraicEquation/solver.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.5/cppNum/approximation.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.5/cppNum/algebraicEquation/solver.cpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.5/cppNum/algebraicEquation/equation.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.5/cppNum/algebraicEquation/newton.cpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.5/cppNum/derivative.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.5/cppNum/algebraicEquation/equation.hpp
