include ../Makefile.inc

# DO NOT DELETE

main.o: lotkaVolterra.hpp
main.o: ../../cppNum/differentialSystem/system.hpp
main.o: ../../cppNum/differentialSystem/implicitEuler.hpp
main.o: ../../cppNum/differentialSystem/integrator.hpp
main.o: ../../cppNum/evolution.hpp
main.o: ../../cppNum/iteration.hpp
main.o: ../../cppNum/linearAlgebra.hpp
main.o: ../../cppNum/differentialSystem/system.hpp
