include ./Makefile.inc
# DO NOT DELETE

main.o: ./f.hpp
main.o: $(BASE_DIR)/cppNum/convexObjective/objective.hpp
main.o: $(BASE_DIR)/cppNum/convexObjective/newton.hpp
main.o: $(BASE_DIR)/cppNum/convexObjective/minimizer.hpp
main.o: $(BASE_DIR)/cppNum/approximation.hpp
main.o: $(BASE_DIR)/cppNum/iteration.hpp
main.o: $(BASE_DIR)/cppNum/linearAlgebra.hpp
main.o: $(BASE_DIR)/cppNum/derivative.hpp
main.o: $(BASE_DIR)/cppNum/exceptions/cppNum_exception.hpp
main.o: $(BASE_DIR)/cppNum/exceptions/logic_error.hpp
main.o: $(BASE_DIR)/cppNum/exceptions/math_error.hpp
