include ../Makefile.inc

# DO NOT DELETE

main.o: $(BASE_DIR)/cppNum/differentialEquation/equation.hpp
main.o: $(BASE_DIR)/cppNum/differentialEquation/explicitEuler.hpp
main.o: $(BASE_DIR)/cppNum/differentialEquation/integrator.hpp
main.o: $(BASE_DIR)/cppNum/evolution.hpp
main.o: $(BASE_DIR)/cppNum/iteration.hpp
main.o: $(BASE_DIR)/cppNum/evolution.cpp
main.o: $(BASE_DIR)/cppNum/differentialEquation/integrator.cpp
main.o: $(BASE_DIR)/cppNum/differentialEquation/equation.hpp
main.o: $(BASE_DIR)/cppNum/differentialEquation/explicitEuler.cpp
