include ../../Makefile.inc

# DO NOT DELETE

main.o: /home/uwe/Documents/git/stce/cppNum/v2.1/apps/intersection/intersection.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v2.1/cppNum/algebraicSystem/system.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v2.1/cppNum/linearAlgebra.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v2.1/cppNum/algebraicSystem/newton.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v2.1/cppNum/algebraicSystem/solver.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v2.1/cppNum/approximation.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v2.1/cppNum/iteration.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v2.1/cppNum/linearAlgebra.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v2.1/cppNum/derivative.hpp
