include ../../Makefile.inc

# DO NOT DELETE

main.o: ../../../cppNum/algebraicEquation/equation.hpp
main.o: ../../../cppNum/algebraicEquation/newton.hpp
main.o: ../../../cppNum/algebraicEquation/solver.hpp
main.o: ../../../cppNum/approximation.hpp
main.o: ../../../cppNum/iteration.hpp
main.o: ../../../cppNum/iteration.cpp
main.o: ../../../cppNum/approximation.cpp
main.o: ../../../cppNum/algebraicEquation/solver.cpp
main.o: ../../../cppNum/algebraicEquation/equation.hpp
main.o: ../../../cppNum/algebraicEquation/newton.cpp
main.o: ../../../cppNum/derivative.hpp
