include ../Makefile.inc

# DO NOT DELETE

main.o: lotkaVolterra.hpp
main.o: $(BASE_DIR)/cppNum/differentialSystem/system.hpp
main.o: $(BASE_DIR)/cppNum/linearAlgebra.hpp
main.o: $(BASE_DIR)/cppNum/differentialSystem/explicitEuler.hpp
main.o: $(BASE_DIR)/cppNum/differentialSystem/integrator.hpp
main.o: $(BASE_DIR)/cppNum/evolution.hpp
main.o: $(BASE_DIR)/cppNum/iteration.hpp
main.o: $(BASE_DIR)/cppNum/linearAlgebra.hpp
main.o: $(BASE_DIR)/cppNum/differentialSystem/system.hpp
