include ../Makefile.inc

# DO NOT DELETE

main.o: /home/uwe/Documents/git/stce/cppNum/v1.4/apps/objectives/f1.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.4/cppNum/convexObjective/objective.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.4/cppNum/convexObjective/newton.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.4/cppNum/convexObjective/minimizer.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.4/cppNum/approximation.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.4/cppNum/iteration.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.4/cppNum/iteration.cpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.4/cppNum/convexObjective/minimizer.cpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.4/cppNum/convexObjective/objective.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.4/cppNum/convexObjective/newton.cpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.4/cppNum/derivative.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.4/cppNum/algebraicEquation/newton.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.4/cppNum/algebraicEquation/solver.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.4/cppNum/algebraicEquation/equation.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.4/cppNum/algebraicEquation/solver.cpp
