# info@stce.rwth-aachen.de

all :
	cd algebraicEquation && make
	cd convexObjective && make
	cd casestudies && make
test :
	cd algebraicEquation && make test
	cd convexObjective && make test
	cd casestudies && make test
depend :
	cd algebraicEquation && make depend
	cd convexObjective && make depend
	cd casestudies && make depend
clean :
	cd algebraicEquation && make clean
	cd convexObjective && make clean
	cd casestudies && make clean

.PHONY: all test depend clean
