include ../Makefile.inc

# DO NOT DELETE

main.o: /home/uwe/Documents/git/stce/cppNum/v1.5/cppNum/algebraicEquation/equation.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.5/cppNum/algebraicEquation/newton.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.5/cppNum/algebraicEquation/solver.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.5/cppNum/approximation.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.5/cppNum/iteration.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.5/cppNum/algebraicEquation/solver.cpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.5/cppNum/algebraicEquation/equation.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.5/cppNum/algebraicEquation/newton.cpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.5/cppNum/derivative.hpp
