include ../../Makefile.inc

# DO NOT DELETE

main.o: ../../../cppNum/differentialEquation/equation.hpp
main.o: ../../../cppNum/differentialEquation/explicitEuler.hpp
main.o: ../../../cppNum/differentialEquation/integrator.hpp
main.o: ../../../cppNum/evolution.hpp
main.o: ../../../cppNum/iteration.hpp
main.o: ../../../cppNum/evolution.cpp
main.o: ../../../cppNum/differentialEquation/integrator.cpp
main.o: ../../../cppNum/differentialEquation/equation.hpp
main.o: ../../../cppNum/differentialEquation/explicitEuler.cpp
