include ../../Makefile.inc

# DO NOT DELETE

main.o: /home/uwe/Documents/git/stce/cppNum/v1.3/apps/objectives/f1.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.3/cppNum/convexObjective/objective.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.3/cppNum/convexObjective/gradientDescent.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.3/cppNum/convexObjective/minimizer.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.3/cppNum/approximation.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.3/cppNum/iteration.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.3/cppNum/convexObjective/minimizer.cpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.3/cppNum/convexObjective/objective.hpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.3/cppNum/convexObjective/gradientDescent.cpp
main.o: /home/uwe/Documents/git/stce/cppNum/v1.3/cppNum/derivative.hpp
