# info@stce.rwth-aachen.de

all :
	cd algebraicEquation && make
test :
	cd algebraicEquation && make test
depend :
	cd algebraicEquation && make depend
clean :
	cd algebraicEquation && make clean

.PHONY: all test depend clean
