include ../Makefile.inc

# DO NOT DELETE

main.o: ../objectives/f1.hpp
main.o: ../../cppNum/convexObjective/objective.hpp
main.o: ../../cppNum/convexObjective/gradientDescent.hpp
main.o: ../../cppNum/convexObjective/minimizer.hpp
main.o: ../../cppNum/approximation.hpp
main.o: ../../cppNum/iteration.hpp
main.o: ../../cppNum/convexObjective/minimizer.cpp
main.o: ../../cppNum/convexObjective/objective.hpp
main.o: ../../cppNum/convexObjective/gradientDescent.cpp
main.o: ../../cppNum/derivative.hpp
