include ../../Makefile.inc

# DO NOT DELETE

main.o: ../../objectives/f1.hpp
main.o: $(BASE_DIR)/cppNum/convexObjective/objective.hpp
main.o: $(BASE_DIR)/cppNum/convexObjective/newton.hpp
main.o: $(BASE_DIR)/cppNum/convexObjective/minimizer.hpp
main.o: $(BASE_DIR)/cppNum/approximation.hpp
main.o: $(BASE_DIR)/cppNum/iteration.hpp
main.o: $(BASE_DIR)/cppNum/iteration.cpp
main.o: $(BASE_DIR)/cppNum/convexObjective/minimizer.cpp
main.o: $(BASE_DIR)/cppNum/convexObjective/objective.hpp
main.o: $(BASE_DIR)/cppNum/convexObjective/newton.cpp
main.o: $(BASE_DIR)/cppNum/derivative.hpp
main.o: $(BASE_DIR)/cppNum/algebraicEquation/newton.hpp
main.o: $(BASE_DIR)/cppNum/algebraicEquation/solver.hpp
main.o: $(BASE_DIR)/cppNum/algebraicEquation/equation.hpp
main.o: $(BASE_DIR)/cppNum/algebraicEquation/solver.cpp
