include ../../Makefile.inc
# DO NOT DELETE

main.o: ../sphere.hpp
main.o: $(BASE_DIR)/cppNum/convexObjective/objective.hpp
main.o: $(BASE_DIR)/cppNum/convexObjective/newton.hpp
main.o: $(BASE_DIR)/cppNum/convexObjective/minimizer.hpp
main.o: $(BASE_DIR)/cppNum/approximation.hpp
main.o: $(BASE_DIR)/cppNum/iteration.hpp
main.o: $(BASE_DIR)/cppNum/linearAlgebra.hpp
main.o: $(BASE_DIR)/cppNum/derivative.hpp
main.o: $(BASE_DIR)/cppNum/exceptions/is_approx.hpp
main.o: $(BASE_DIR)/cppNum/exceptions/logic_error.hpp
main.o: $(BASE_DIR)/cppNum/exceptions/math_error.hpp
