# info@stce.rwth-aachen.de

all :
	cd ad && make
	cd fd && make
	cd visualization && make
test :
	cd ad && make test
	cd fd && make test
	cd visualization && make test
depend :
	cd ad && make depend
	cd fd && make depend
	cd visualization && make depend
clean :
	cd ad && make clean
	cd fd && make clean
	cd visualization && make clean

.PHONY: all test depend clean
