include ../Makefile.inc

# DO NOT DELETE

main.o: $(BASE_DIR)/cppNum/algebraicEquation/equation.hpp
main.o: $(BASE_DIR)/cppNum/algebraicEquation/newton.hpp
main.o: $(BASE_DIR)/cppNum/algebraicEquation/solver.hpp
main.o: $(BASE_DIR)/cppNum/approximation.hpp
main.o: $(BASE_DIR)/cppNum/iteration.hpp
main.o: $(BASE_DIR)/cppNum/iteration.cpp
main.o: $(BASE_DIR)/cppNum/algebraicEquation/equation.hpp
main.o: $(BASE_DIR)/cppNum/algebraicEquation/solver.cpp
main.o: $(BASE_DIR)/cppNum/algebraicEquation/newton.cpp
main.o: $(BASE_DIR)/cppNum/derivative.hpp
